import { expect, test } from '@playwright/test'

test('debug garden skips the first two acts and starts a fresh third act', async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.setItem('life-backtest.garden.v2', JSON.stringify({
      version: 2,
      profile: { age: '24', gender: '演示', family: '演示 · 与父母同住', status: '演示 · 学生', rewind: '18岁' },
      currentAge: 24,
      target: { raw: '18岁', kind: 'age', age: 18, year: null },
      selectedAge: 24,
      planted: [{ age: 18, choiceId: 'college' }, { age: 25, choiceId: 'second' }],
      records: [],
      recordedAt: '2026-01-01T00:00:00.000Z',
      reachedPresent: true,
    }))
  })
  await page.setViewportSize({ width: 1536, height: 864 })
  await page.goto('/?debug=garden')
  const garden = page.locator('.garden-scene')
  await expect(garden).toBeVisible()
  await expect(page.getByRole('button', { name: '个人标签' })).toBeVisible()
  await expect(page.locator('.opening-scene')).toBeHidden()
  await expect(page.locator('.archive-scene')).toBeHidden()
  await expect(garden).toHaveAttribute('data-garden-phase', 'era')
  await expect(garden).toHaveAttribute('data-current-age', '24')
  await expect(garden).toHaveAttribute('data-target-age', '18')
  await expect(page.getByRole('button', { name: '25岁', exact: true })).toHaveCount(0)
  await expect(page.locator('.garden-ground-flower')).toHaveCount(0)
  await page.getByRole('button', { name: '登记资料', exact: true }).click()
  await expect(page.locator('.garden-profile')).toContainText('演示 · 学生')
})

test('timeline uses five-year nodes, era copy, ship flowers and two-click planting', async ({ page }) => {
  test.setTimeout(150_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 1536, height: 864 })
  await page.goto('/?scene=garden')
  const garden = page.locator('.garden-scene')
  await expect(garden).toBeVisible()
  await expect(page.locator('.garden-choice-flower')).toHaveCount(0)
  await expect(page.locator('.garden-signals')).toBeHidden()
  await expect(page.getByRole('heading', { level: 1 })).toContainText('岁')
  await expect(page.locator('.garden-note')).not.toHaveText('')
  await page.getByRole('button', { name: '确认回溯年龄 →' }).click()
  await page.getByRole('textbox', { name: '确认回溯年龄', exact: true }).fill('22')
  await page.getByRole('button', { name: '记录', exact: true }).click()
  await expect(garden).toHaveAttribute('data-age', '22')
  await expect(garden).toHaveAttribute('data-garden-phase', 'era')
  await page.getByRole('button', { name: '20岁', exact: true }).click()
  await expect(garden).toHaveAttribute('data-garden-phase', 'choices')
  await expect(page.locator('.garden-choice-stats')).toContainText('%')
  await expect(page.locator('.garden-choice-flower.is-landed')).toHaveCount(3, { timeout: 4000 })
  await expect(page.locator('.garden-signals')).toBeHidden()
  await page.screenshot({ path: 'playtest/garden-01-hover.png' })
  const firstFlower = page.locator('.garden-choice-flower').first()
  await firstFlower.click()
  await expect(garden).toHaveAttribute('data-garden-phase', 'inspect')
  await expect(garden).toHaveAttribute('data-signal-mode', 'inspect')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('这朵花代表')
  await expect(page.locator('.garden-signal-reason')).toContainText('% 的同龄人选择')
  await expect(page.locator('.garden-signal-reason')).toContainText('把专业读完')
  await page.screenshot({ path: 'playtest/garden-01b-reason.png' })
  await firstFlower.click()
  await expect(garden).toHaveAttribute('data-actor-phase', 'walking')
  await page.waitForTimeout(850)
  await page.screenshot({ path: 'playtest/garden-motion-01-walking.png' })
  await expect(garden).toHaveAttribute('data-actor-phase', 'kneeling', { timeout: 8000 })
  await page.waitForTimeout(420)
  await page.screenshot({ path: 'playtest/garden-motion-02-kneeling.png' })
  await expect(page.locator('.garden-ground-flower')).toHaveClass(/is-planting/, { timeout: 8000 })
  await page.screenshot({ path: 'playtest/garden-02-growing.png' })
  await expect(page.locator('.garden-ground-flower')).toHaveAttribute('data-planted', 'true', { timeout: 12_000 })
  await expect(garden).toHaveAttribute('data-age', '22')
  await expect(garden).toHaveAttribute('data-garden-phase', 'era')
  await expect(page.locator('.garden-signals')).toBeHidden()
  await expect(page.getByRole('heading', { level: 1 })).toContainText('22岁')
  await page.getByRole('button', { name: '20岁', exact: true }).click()
  await expect(page.locator('.garden-choice-flower.is-landed')).toHaveCount(3, { timeout: 4000 })
  await firstFlower.click()
  await firstFlower.click()
  await expect(garden).toHaveAttribute('data-actor-phase', 'idle', { timeout: 12_000 })
  await expect(garden).toHaveAttribute('data-garden-phase', 'npc')
  await expect(garden).toHaveAttribute('data-signal-mode', 'npc')
  await expect(page.locator('.garden-signal-npc')).toHaveCount(3)
  await expect(page.locator('.garden-signals')).toContainText('本地画像')
  await page.getByRole('button', { name: /同代 · 相近选择/ }).click()
  await expect(page.locator('.garden-signal-card')).toContainText('背景')
  await expect(page.locator('.garden-signal-chain')).toContainText('选项')
  await expect(page.locator('.garden-signal-chain')).toContainText('选择')
  await expect(page.locator('.garden-signal-chain')).toContainText('代价')
  await expect(page.locator('.garden-signal-chain')).toContainText('反思')
  await page.screenshot({ path: 'playtest/garden-03-npc-card.png' })
  await page.getByRole('button', { name: '收起画像' }).click()
  await expect(page.locator('.garden-signal-npc')).toHaveCount(3)
  await page.getByRole('button', { name: '登记资料' }).click()
  await expect(page.locator('.garden-panel-title')).toContainText('你留下的起点')
  await page.getByRole('button', { name: '关闭时间档案' }).click()
  const feetBefore = await garden.getAttribute('data-actor-x')
  await page.keyboard.press('ArrowRight')
  await expect(garden).toHaveAttribute('data-age', '22')
  await expect(garden).toHaveAttribute('data-garden-phase', 'era')
  await page.keyboard.press('ArrowRight')
  await expect(garden).toHaveAttribute('data-age', '25')
  await page.keyboard.press('ArrowLeft')
  await expect(garden).toHaveAttribute('data-age', '22')
  await expect(garden).toHaveAttribute('data-actor-x', feetBefore!)
  await page.getByRole('button', { name: '40岁以后的时光 →' }).click()
  await expect(garden).toHaveAttribute('data-age', '40')
  await page.getByRole('button', { name: '60岁', exact: true }).click()
  await expect(page.locator('.garden-choice-flower.is-landed')).toHaveCount(3, { timeout: 4000 })
  await page.locator('.garden-choice-flower').first().click()
  await page.locator('.garden-choice-flower').first().click()
  await expect(page.locator('.garden-ground-flower[data-age="60"]')).toHaveAttribute('data-planted', 'true', { timeout: 18_000 })
  await page.getByRole('button', { name: '80岁', exact: true }).click()
  await expect(garden).toHaveAttribute('data-age', '80')
  await page.screenshot({ path: 'playtest/garden-04-eighty.png' })
  await page.getByRole('button', { name: '回到回溯起点 ↖' }).click()
  await expect(garden).toHaveAttribute('data-age', '22')
  await page.reload()
  await expect(garden).toHaveAttribute('data-age', '22')
  await expect(page.locator('.garden-signals')).toBeHidden()
  expect(errors).toEqual([])
})

test('the garden stays usable in portrait and with reduced motion', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/?scene=garden')
  await expect(page.locator('.garden-scene')).toBeVisible()
  await page.getByRole('button', { name: '确认回溯年龄 →' }).click()
  await page.getByRole('textbox', { name: '确认回溯年龄', exact: true }).fill('35')
  await page.getByRole('button', { name: '记录', exact: true }).click()
  await page.getByRole('button', { name: '35岁', exact: true }).click()
  await expect(page.locator('.garden-choice-flower.is-landed')).toHaveCount(3)
  await page.locator('.garden-choice-flower').nth(1).click()
  await page.locator('.garden-choice-flower').nth(1).click()
  await expect(page.locator('.garden-scene')).toHaveAttribute('data-age', '40', { timeout: 18_000 })
  await expect(page.locator('.garden-scene')).toHaveAttribute('data-garden-phase', 'era')
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('life-backtest.garden.v2') || '{}').planted)).toEqual([{ age: 35, choiceId: 'sprint' }])
  await page.screenshot({ path: 'playtest/garden-05-portrait.png', fullPage: true })
  expect(await page.locator('.garden-frame').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
})

test('R interrupts travel without teleporting, planting or overwriting the selected age', async ({ page }) => {
  await page.goto('/?scene=garden')
  const garden = page.locator('.garden-scene')
  await page.getByRole('button', { name: '0岁', exact: true }).click()
  await expect(page.locator('.garden-choice-flower.is-landed')).toHaveCount(3, { timeout: 4000 })
  await page.locator('.garden-choice-flower').first().click()
  await page.locator('.garden-choice-flower').first().click()
  await expect(garden).toHaveAttribute('data-actor-phase', 'walking')
  await page.waitForTimeout(800)
  await page.keyboard.press('r')
  await expect(garden).toHaveAttribute('data-actor-phase', 'idle')
  const feet = await garden.getAttribute('data-actor-x')
  await page.waitForTimeout(1200)
  await expect(garden).toHaveAttribute('data-actor-x', feet!)
  await expect(garden).toHaveAttribute('data-age', '0')
  await expect(page.locator('.garden-ground-flower')).toHaveCount(0)
  await page.getByRole('button', { name: '与主角打个招呼' }).click()
  await expect(page.locator('.garden-note')).toContainText('先点时间线上的一年')
  await page.screenshot({ path: 'playtest/garden-motion-03-cancel.png' })
})

test('planting up to the present age opens four holes, then boarding enters backtrack', async ({ page }) => {
  test.setTimeout(90_000)
  await page.addInitScript(() => {
    sessionStorage.setItem('life-backtest.archive-profile', JSON.stringify({
      age: '22', rewind: '20岁', gender: '演示', family: '演示', status: '演示',
    }))
    localStorage.removeItem('life-backtest.garden.v2')
  })
  await page.setViewportSize({ width: 1536, height: 864 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/?scene=garden')
  const garden = page.locator('.garden-scene')
  await expect(garden).toBeVisible()
  await expect(garden).toHaveAttribute('data-current-age', '22')
  await expect(garden).toHaveAttribute('data-garden-phase', 'era')
  await expect(page.getByRole('button', { name: '25岁', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '30岁', exact: true })).toHaveCount(0)
  await expect(page.locator('[data-action="chapters"]')).toBeHidden()
  await page.getByRole('button', { name: '20岁', exact: true }).click()
  await expect(page.locator('.garden-choice-flower.is-landed')).toHaveCount(3, { timeout: 4000 })
  await page.locator('.garden-choice-flower').first().click()
  await page.locator('.garden-choice-flower').first().click()
  await expect(garden).toHaveAttribute('data-garden-phase', 'crossroads', { timeout: 18_000 })
  await expect(page.locator('.garden-copy')).toBeHidden()
  await expect(page.locator('.garden-timeline')).toBeHidden()
  await expect(page.locator('.garden-signals')).toBeHidden()
  await expect(page.getByRole('button', { name: '回溯 · 重访没选的那条路' })).toBeVisible()
  await expect(page.getByRole('button', { name: '前进 · 跟随相近人生继续' })).toBeVisible()
  await expect(page.getByRole('button', { name: '前瞻 · 看 25–27 岁的可能' })).toBeVisible()
  await expect(page.getByRole('button', { name: '结束 · 把选择链看成自己的' })).toBeVisible()
  await expect(page.locator('.garden-hole-world')).toHaveCount(4)
  await expect(page.locator('.garden-hole-core')).toHaveCount(0)
  await page.screenshot({ path: 'playtest/garden-06-crossroads.png' })
  await page.getByRole('button', { name: '回溯 · 重访没选的那条路' }).click()
  await expect(page.locator('.garden-rift')).toBeVisible({ timeout: 8_000 })
  await expect(page.locator('.garden-rift')).toHaveClass(/is-visible/)
  await expect(garden).toHaveAttribute('data-garden-phase', 'rift')
  await expect(page.locator('.garden-background')).toBeVisible()
  await expect(page.locator('.garden-player')).toBeVisible()
  await expect(page.locator('.garden-ground-flower.is-rift-pick')).toBeVisible()
  await expect(page.getByText('你走过的轨迹')).toBeVisible()
  await expect(page.locator('.garden-rift-trail-star')).toHaveCount(1)
  await expect(page.locator('.garden-rift-journey')).toHaveCount(0)
  await expect(page.locator('.garden-rift-planet')).toHaveCount(0)
  await expect(page.getByRole('heading', { name: '你想回到哪一个没想通的节点？' })).toBeVisible()
  await expect(page.getByText('演示内容 · 不是真实匹配结果')).toBeVisible()
  await page.locator('.garden-ground-flower.is-rift-pick').first().click()
  await expect(page.locator('.garden-rift-trail')).toHaveCount(0)
  await expect(page.locator('.garden-rift-lead')).toContainText('未选择之路')
  await expect(page.locator('.garden-rift-alt').first()).toContainText('如果你当时选了')
  await page.locator('.garden-rift-alt').first().click()
  await expect(page.locator('.garden-rift-post')).toContainText('如果选了')
  await expect(page.locator('.garden-rift-post')).toContainText('阅读原文')
  await page.screenshot({ path: 'playtest/garden-07-backtrack.png' })
  await page.getByRole('button', { name: '返回三岔口' }).first().click()
  await expect(garden).toHaveAttribute('data-garden-phase', 'crossroads')
  await page.getByRole('button', { name: '前进 · 跟随相近人生继续' }).click()
  await expect(page.getByText('概率推演，非命运定论')).toBeVisible({ timeout: 8_000 })
  await page.locator('.garden-rift-npc').first().click()
  await expect(page.locator('.garden-rift-dossier')).toBeVisible()
  await expect(page.locator('.garden-rift-beat')).toHaveCount(3)
  await expect(page.locator('.garden-rift-options button')).toHaveCount(0)
  await expect(page.locator('.garden-rift-dossier-choice')).toContainText('%')
  await expect(page.locator('.garden-rift-archive-post')).toHaveCount(3)
  await expect(page.locator('.garden-rift-archive')).toContainText('TA 写过的')
  await page.getByRole('button', { name: '返回三岔口' }).first().click()
  await expect(garden).toHaveAttribute('data-garden-phase', 'crossroads')
  await page.getByRole('button', { name: '前瞻 · 看 25–27 岁的可能' }).click()
  await expect(page.getByRole('heading', { name: '25 → 26 → 27 岁可能的走向' })).toBeVisible({ timeout: 8_000 })
  await expect(page.getByText('不是命运定论')).toBeVisible()
  await expect(page.getByRole('button', { name: '个人标签' })).toBeVisible()
  await page.getByRole('button', { name: '写下个人展望' }).click()
  await expect(page.locator('.personal-tag-panel')).toBeVisible()
  await expect(page.locator('.personal-tag-profile')).toContainText('现在的年龄')
  await expect(page.locator('.personal-tag-profile')).toContainText('24')
  await expect(page.locator('.personal-tag-choices')).toContainText('岁')
  await page.locator('.personal-tag-form textarea[name="plans"]').fill('先验证再决定')
  await page.locator('.personal-tag-form button[type="submit"]').click()
  await expect(page.locator('.personal-tag-panel')).toBeHidden()
  await page.getByRole('button', { name: '返回三岔口' }).first().click()
  await page.getByRole('button', { name: '结束 · 把选择链看成自己的' }).click()
  await expect(page.getByRole('heading', { name: /有了不一样的体会/ })).toBeVisible({ timeout: 8_000 })
  await expect(page.getByText('阅读原文（演示）')).toBeVisible()
  await page.getByRole('button', { name: '返回三岔口' }).first().click()
  await expect(garden).toHaveAttribute('data-garden-phase', 'crossroads')
})
