import { expect, test } from '@playwright/test'

test('debug garden skips the first two acts and starts a fresh third act', async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.setItem('life-backtest.garden.v2', JSON.stringify({
      version: 2,
      profile: { age: '24', gender: '演示', family: '演示 · 与父母同住', status: '演示 · 学生', rewind: '18岁' },
      currentAge: 24,
      target: { raw: '18岁', kind: 'age', age: 18, year: null },
      selectedAge: 24,
      planted: [{ age: 18, choiceId: 'college' }, { age: 25, choiceId: 'second' }],
      records: [],
      recordedAt: '2026-01-01T00:00:00.000Z',
      reachedPresent: true,
    }))
  })
  await page.setViewportSize({ width: 1536, height: 864 })
  await page.goto('/?debug=garden&reset=1')
  const garden = page.locator('.garden-scene')
  await expect(garden).toBeVisible()
  await expect(page.getByRole('button', { name: '个人标签' })).toBeVisible()
  await expect(page.locator('.opening-scene')).toBeHidden()
  await expect(page.locator('.archive-scene')).toBeHidden()
  await expect(garden).toHaveAttribute('data-garden-phase', 'era')
  await expect(garden).toHaveAttribute('data-current-age', '24')
  await expect(garden).toHaveAttribute('data-target-age', '18')
  await expect(page.getByRole('button', { name: '25岁', exact: true })).toHaveCount(0)
  await expect(page.locator('.garden-ground-flower')).toHaveCount(0)
  await page.getByRole('button', { name: '个人标签' }).click()
  await expect(page.locator('.personal-tag-profile')).toContainText('演示 · 学生')
})

test('looking back at a planted year does not grow a second flower', async ({ page }) => {
  await page.addInitScript(() => localStorage.removeItem('life-backtest.garden.v2'))
  await page.setViewportSize({ width: 1536, height: 864 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/?debug=garden')
  const garden = page.locator('.garden-scene')
  await page.getByRole('button', { name: '0岁', exact: true }).click()
  const first = page.locator('.garden-choice-flower').first()
  await expect(first).toBeVisible({ timeout: 4000 })
  await first.click()
  await first.click()
  await expect(page.locator('.garden-ground-flower[data-age="0"]')).toHaveCount(1, { timeout: 18_000 })
  await page.getByRole('button', { name: '进入下一个时间点 →' }).click()
  await page.getByRole('button', { name: '5岁', exact: true }).click()
  const five = page.locator('.garden-choice-flower').first()
  await expect(five).toBeVisible({ timeout: 4000 })
  await five.click()
  await five.click()
  await expect(page.locator('.garden-ground-flower[data-age="5"]')).toHaveCount(1, { timeout: 18_000 })
  await page.getByRole('button', { name: '0岁', exact: true }).click()
  const other = page.locator('.garden-choice-flower.is-landed').nth(1)
  await expect(other).toBeVisible({ timeout: 4000 })
  await other.click()
  await other.click()
  await expect(garden).toHaveAttribute('data-actor-phase', 'idle', { timeout: 12_000 })
  await expect(page.locator('.garden-ground-flower[data-age="0"]')).toHaveCount(1)
  await expect(page.locator('.garden-ground-flower[data-age="5"]')).toHaveCount(1)
})

test('age 5 keeps the usual forks and treats dance as part of art school', async ({ page }) => {
  await page.addInitScript(() => localStorage.removeItem('life-backtest.garden.v2'))
  await page.setViewportSize({ width: 1536, height: 864 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/?debug=garden')
  await page.getByRole('button', { name: '5岁', exact: true }).click()
  await expect(page.getByRole('button', { name: '上幼儿园', exact: true })).toBeVisible({ timeout: 4000 })
  await expect(page.getByRole('button', { name: '去艺校', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '在家自育 / 跟随父母迁移', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '提前上小学 / 跳级', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '这一年常往医院跑', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '去舞校', exact: true })).toHaveCount(0)
  await expect(page.locator('.garden-choice-flower[aria-label="去舞校 / 武校 / 艺校"]')).toHaveCount(0)
  await page.screenshot({ path: 'playtest/garden-05-art-school.png' })
})

test('at 24, planting age 20 shows sky NPCs then the 24-year era, not the ending', async ({ page }) => {
  await page.addInitScript(() => localStorage.removeItem('life-backtest.garden.v2'))
  await page.setViewportSize({ width: 1536, height: 864 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/?debug=garden')
  const garden = page.locator('.garden-scene')
  await expect(garden).toBeVisible()
  await expect(garden).toHaveAttribute('data-current-age', '24')
  await expect(page.getByRole('button', { name: '24岁', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '20岁', exact: true }).click()
  await expect(page.locator('.garden-choice-flower.is-landed').first()).toBeVisible({ timeout: 4000 })
  await page.locator('.garden-choice-flower').first().click()
  await page.locator('.garden-choice-flower').first().click()
  await expect(garden).toHaveAttribute('data-garden-phase', 'npc', { timeout: 18_000 })
  await expect(garden).toHaveAttribute('data-age', '20')
  await expect.poll(async () => page.locator('.garden-signal-npc').count()).toBeGreaterThanOrEqual(2)
  await expect(page.locator('.garden-signals')).not.toContainText('同代旁路')
  await expect(page.locator('.garden-signals')).toContainText('飞船上方的推荐帖')
  await page.getByRole('button', { name: /A · 同代相近/ }).click()
  await expect(page.locator('.garden-signal-card')).toBeVisible()
  await expect(page.locator('.garden-signal-story')).toBeVisible()
  await expect(page.locator('.garden-signal-card')).not.toContainText('检索')
  await expect(page.locator('.garden-signal-source')).toBeVisible()
  await page.getByRole('button', { name: '进入下一个时间点 →' }).click()
  await expect(garden).toHaveAttribute('data-age', '24')
  await expect(garden).toHaveAttribute('data-garden-phase', 'era')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('24岁')
  await expect(page.locator('.garden-signals')).toBeHidden()
})

test('planting at 40 keeps earlier flowers on the planet', async ({ page }) => {
  await page.addInitScript(() => localStorage.removeItem('life-backtest.garden.v2'))
  await page.setViewportSize({ width: 1536, height: 864 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/?debug=garden&age=40')
  const garden = page.locator('.garden-scene')
  await expect(garden).toHaveAttribute('data-current-age', '40')
  await page.getByRole('button', { name: '20岁', exact: true }).click()
  await expect(page.locator('.garden-choice-flower.is-landed').first()).toBeVisible({ timeout: 4000 })
  await page.locator('.garden-choice-flower').first().click()
  await page.locator('.garden-choice-flower').first().click()
  await expect(page.locator('.garden-ground-flower[data-age="20"]')).toHaveAttribute('data-planted', 'true', { timeout: 18_000 })
  await page.getByRole('button', { name: '40岁', exact: true }).click()
  await expect(page.locator('.garden-choice-flower.is-landed').first()).toBeVisible({ timeout: 4000 })
  await page.locator('.garden-choice-flower').first().click()
  await page.locator('.garden-choice-flower').first().click()
  await expect(page.locator('.garden-ground-flower[data-age="40"]')).toHaveAttribute('data-planted', 'true', { timeout: 18_000 })
  await expect(page.locator('.garden-ground-flower[data-age="20"]')).toBeVisible()
  await expect(page.locator('.garden-ground-flower[data-age="40"]')).toBeVisible()
})

test('timeline uses five-year nodes, era copy, ship flowers and two-click planting', async ({ page }) => {
  test.setTimeout(150_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 1536, height: 864 })
  await page.goto('/?scene=garden')
  const garden = page.locator('.garden-scene')
  await expect(garden).toBeVisible()
  await expect(page.locator('.garden-timeline')).toBeVisible()
  await expect(page.getByRole('button', { name: '0岁', exact: true })).toBeVisible()
  await expect(page.locator('.garden-choice-flower')).toHaveCount(0)
  await expect(page.locator('.garden-signals')).toBeHidden()
  await expect(page.getByRole('heading', { level: 1 })).toContainText('岁')
  await expect(page.locator('.garden-note')).not.toHaveText('')
  await page.getByRole('button', { name: '确认回溯年龄 →' }).click()
  await page.getByRole('textbox', { name: '确认回溯年龄', exact: true }).fill('22')
  await page.getByRole('button', { name: '记录', exact: true }).click()
  await expect(garden).toHaveAttribute('data-age', '22')
  await expect(garden).toHaveAttribute('data-garden-phase', 'era')
  await page.getByRole('button', { name: '20岁', exact: true }).click()
  await expect(garden).toHaveAttribute('data-garden-phase', 'choices')
  await expect(page.locator('.garden-choice-stats')).toContainText('%')
  await expect.poll(async () => page.locator('.garden-choice-flower.is-landed').count(), { timeout: 4000 }).toBeGreaterThanOrEqual(6)
  await expect(page.locator('.garden-signals')).toBeHidden()
  await page.screenshot({ path: 'playtest/garden-01-hover.png' })
  const firstFlower = page.locator('.garden-choice-flower').first()
  await firstFlower.click()
  await expect(garden).toHaveAttribute('data-garden-phase', 'inspect')
  await expect(garden).toHaveAttribute('data-signal-mode', 'inspect')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('这条路')
  await expect(page.locator('.garden-signal-reason')).toContainText('% 的同龄人选择')
  await expect(page.locator('.garden-signal-reason')).toContainText('把专业读完')
  await page.screenshot({ path: 'playtest/garden-01b-reason.png' })
  await firstFlower.click()
  await expect(garden).toHaveAttribute('data-actor-phase', 'walking')
  await page.waitForTimeout(850)
  await page.screenshot({ path: 'playtest/garden-motion-01-walking.png' })
  await expect(garden).toHaveAttribute('data-actor-phase', 'kneeling', { timeout: 8000 })
  await page.waitForTimeout(420)
  await page.screenshot({ path: 'playtest/garden-motion-02-kneeling.png' })
  await expect(page.locator('.garden-ground-flower')).toHaveClass(/is-planting/, { timeout: 8000 })
  await page.screenshot({ path: 'playtest/garden-02-growing.png' })
  await expect(page.locator('.garden-ground-flower')).toHaveAttribute('data-planted', 'true', { timeout: 12_000 })
  await expect(garden).toHaveAttribute('data-age', '20')
  await expect(garden).toHaveAttribute('data-garden-phase', 'npc')
  await expect.poll(async () => page.locator('.garden-signal-npc').count()).toBeGreaterThanOrEqual(2)
  await expect(page.locator('.garden-signals')).not.toContainText('同代旁路')
  await page.getByRole('button', { name: '进入下一个时间点 →' }).click()
  await expect(garden).toHaveAttribute('data-age', '22')
  await expect(garden).toHaveAttribute('data-garden-phase', 'era')
  await expect(page.locator('.garden-signals')).toBeHidden()
  await expect(page.getByRole('heading', { level: 1 })).toContainText('22岁')
  await page.getByRole('button', { name: '20岁', exact: true }).click()
  await expect.poll(async () => page.locator('.garden-choice-flower.is-landed').count(), { timeout: 4000 }).toBeGreaterThanOrEqual(6)
  await firstFlower.click()
  await firstFlower.click()
  await expect(garden).toHaveAttribute('data-actor-phase', 'idle', { timeout: 12_000 })
  await expect(garden).toHaveAttribute('data-garden-phase', 'npc')
  await expect(garden).toHaveAttribute('data-signal-mode', 'npc')
  await expect.poll(async () => page.locator('.garden-signal-npc').count()).toBeGreaterThanOrEqual(2)
  await expect(page.locator('.garden-signals')).not.toContainText('同代旁路')
  await expect(page.locator('.garden-signals')).toContainText('飞船上方的推荐帖')
  await page.getByRole('button', { name: /A · 同代相近/ }).click()
  await expect(page.locator('.garden-signal-card')).toContainText('选了')
  await expect(page.locator('.garden-signal-story')).toBeVisible()
  await expect(page.locator('.garden-signal-card')).not.toContainText('检索')
  await expect(page.locator('.garden-signal-chain')).toHaveCount(0)
  await page.screenshot({ path: 'playtest/garden-03-npc-card.png' })
  await page.getByRole('button', { name: '收起画像' }).click()
  await expect.poll(async () => page.locator('.garden-signal-npc').count()).toBeGreaterThanOrEqual(2)
  await expect(page.locator('.garden-signals')).not.toContainText('同代旁路')
  await page.getByRole('button', { name: '个人标签' }).click()
  await expect(page.locator('.personal-tag-profile')).toContainText('现在的年龄')
  await page.getByRole('button', { name: '关闭个人标签' }).click()
  const feetBefore = await garden.getAttribute('data-actor-x')
  await page.keyboard.press('ArrowRight')
  await expect(garden).toHaveAttribute('data-age', '22')
  await expect(garden).toHaveAttribute('data-garden-phase', 'era')
  await page.keyboard.press('ArrowRight')
  await expect(garden).toHaveAttribute('data-age', '25')
  await page.keyboard.press('ArrowLeft')
  await expect(garden).toHaveAttribute('data-age', '22')
  await expect(garden).toHaveAttribute('data-actor-x', feetBefore!)
  await page.getByRole('button', { name: '40岁以后的时光 →' }).click()
  await expect(garden).toHaveAttribute('data-age', '40')
  await page.getByRole('button', { name: '60岁', exact: true }).click()
  await expect.poll(async () => page.locator('.garden-choice-flower.is-landed').count(), { timeout: 4000 }).toBeGreaterThanOrEqual(6)
  await page.locator('.garden-choice-flower').first().click()
  await page.locator('.garden-choice-flower').first().click()
  await expect(page.locator('.garden-ground-flower[data-age="60"]')).toHaveAttribute('data-planted', 'true', { timeout: 18_000 })
  await page.getByRole('button', { name: '80岁', exact: true }).click()
  await expect(garden).toHaveAttribute('data-age', '80')
  await page.screenshot({ path: 'playtest/garden-04-eighty.png' })
  await page.getByRole('button', { name: '回到回溯起点 ↖' }).click()
  await expect(garden).toHaveAttribute('data-age', '22')
  await page.reload()
  await expect(garden).toHaveAttribute('data-age', '22')
  await expect(page.locator('.garden-signals')).toBeHidden()
  expect(errors).toEqual([])
})

test('extra flowers sit small on the far horizon, not stacked in the sky', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/?debug=garden')
  await page.getByRole('button', { name: '0岁', exact: true }).click()
  await expect.poll(async () => page.locator('.garden-choice-flower.is-landed').count(), { timeout: 4000 }).toBeGreaterThanOrEqual(7)
  await expect(page.locator('.garden-earth')).toBeVisible()
  const extras = page.locator('.garden-choice-flower[data-lane="starboard"]')
  await expect(extras.first()).toBeVisible()
  const scene = await page.locator('.garden-choice-flowers').boundingBox()
  const boxes = await extras.locator('.garden-choice-halo').evaluateAll(nodes => nodes.map(node => node.getBoundingClientRect()))
  expect(scene).toBeTruthy()
  for (const box of boxes) {
    const mid = box.y + box.height / 2
    expect(mid).toBeGreaterThan(scene!.y + scene!.height * 0.45)
    expect(box.height).toBeLessThan(scene!.height * 0.16)
  }
  const dialog = await page.locator('.garden-copy').boundingBox()
  const caption = await page.locator('.garden-timeline-caption').boundingBox()
  expect(dialog).toBeTruthy()
  expect(caption).toBeTruthy()
  expect(dialog!.y + dialog!.height).toBeLessThan(caption!.y)
  const origin = await page.getByRole('button', { name: '回到回溯起点 ↖' }).boundingBox()
  expect(origin).toBeTruthy()
  for (const box of await extras.evaluateAll(nodes => nodes.map(node => node.getBoundingClientRect()))) {
    const hit = origin!.x < box.x + box.width && origin!.x + origin!.width > box.x && origin!.y < box.y + box.height && origin!.y + origin!.height > box.y
    expect(hit).toBe(false)
  }
  await page.screenshot({ path: 'playtest/garden-starboard-horizon.png', fullPage: true })
})

test('the garden stays usable in portrait and with reduced motion', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/?scene=garden')
  await expect(page.locator('.garden-scene')).toBeVisible()
  await page.getByRole('button', { name: '确认回溯年龄 →' }).click()
  await page.getByRole('textbox', { name: '确认回溯年龄', exact: true }).fill('35')
  await page.getByRole('button', { name: '记录', exact: true }).click()
  await page.getByRole('button', { name: '35岁', exact: true }).click()
  await expect.poll(async () => page.locator('.garden-choice-flower.is-landed').count()).toBeGreaterThanOrEqual(6)
  await page.locator('.garden-choice-flower').nth(1).click()
  await page.locator('.garden-choice-flower').nth(1).click()
  await expect(page.locator('.garden-scene')).toHaveAttribute('data-garden-phase', 'npc', { timeout: 18_000 })
  await page.getByRole('button', { name: '进入下一个时间点 →' }).click()
  await expect(page.locator('.garden-scene')).toHaveAttribute('data-age', '40')
  await expect(page.locator('.garden-scene')).toHaveAttribute('data-garden-phase', 'era')
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('life-backtest.garden.v2') || '{}').planted)).toEqual([{ age: 35, choiceId: 'sprint', label: '再冲一轮事业' }])
  await page.screenshot({ path: 'playtest/garden-05-portrait.png', fullPage: true })
  const letterbox = await page.locator('.garden-frame').boundingBox()
  const viewport = page.viewportSize()!
  expect(letterbox).toBeTruthy()
  expect(letterbox!.width).toBeLessThanOrEqual(viewport.width + 1)
  expect(letterbox!.height).toBeLessThanOrEqual(viewport.height + 1)
  expect(Math.abs(letterbox!.width / letterbox!.height - 1672 / 941)).toBeLessThan(0.03)
  expect(await page.locator('.garden-frame').evaluate(el => getComputedStyle(el).overflow)).toMatch(/hidden/)
})

test('R interrupts travel without teleporting, planting or overwriting the selected age', async ({ page }) => {
  await page.goto('/?scene=garden')
  const garden = page.locator('.garden-scene')
  await page.getByRole('button', { name: '0岁', exact: true }).click()
  await expect.poll(async () => page.locator('.garden-choice-flower.is-landed').count(), { timeout: 4000 }).toBeGreaterThanOrEqual(7)
  const halos = await page.locator('.garden-choice-flower.is-landed .garden-choice-halo').evaluateAll(nodes => nodes.map(node => {
    const box = node.getBoundingClientRect()
    return { x: box.x, y: box.y, r: box.right, b: box.bottom }
  }))
  for (let i = 0; i < halos.length; i++) {
    for (let j = i + 1; j < halos.length; j++) {
      const a = halos[i], next = halos[j]
      const overlap = a.x < next.r && a.r > next.x && a.y < next.b && a.b > next.y
      expect(overlap, `flower halo ${i} overlaps ${j}`).toBe(false)
    }
  }
  const origin = await page.getByRole('button', { name: '回到回溯起点 ↖' }).boundingBox()
  expect(origin).toBeTruthy()
  for (const box of await page.locator('.garden-choice-flower[data-lane="starboard"]').evaluateAll(nodes => nodes.map(node => node.getBoundingClientRect()))) {
    const hit = origin!.x < box.x + box.width && origin!.x + origin!.width > box.x && origin!.y < box.y + box.height && origin!.y + origin!.height > box.y
    expect(hit, 'starboard flower covers 回到回溯起点').toBe(false)
  }
  await page.screenshot({ path: 'playtest/garden-starboard-desktop.png' })
  await page.locator('.garden-choice-flower').first().click()
  await page.locator('.garden-choice-flower').first().click()
  await expect(garden).toHaveAttribute('data-actor-phase', 'walking')
  await page.waitForTimeout(800)
  await page.keyboard.press('r')
  await expect(garden).toHaveAttribute('data-actor-phase', 'idle')
  const feet = await garden.getAttribute('data-actor-x')
  await page.waitForTimeout(1200)
  await expect(garden).toHaveAttribute('data-actor-x', feet!)
  await expect(garden).toHaveAttribute('data-age', '0')
  await expect(page.locator('.garden-ground-flower')).toHaveCount(0)
  await page.getByRole('button', { name: '与主角打个招呼' }).click()
  await expect(page.locator('.garden-note')).toContainText('先点时间线上的一年')
  await page.screenshot({ path: 'playtest/garden-motion-03-cancel.png' })
})

test('planting up to the present age opens three holes, then boarding enters backtrack', async ({ page }) => {
  test.setTimeout(90_000)
  await page.addInitScript(() => {
    sessionStorage.setItem('life-backtest.archive-profile', JSON.stringify({
      age: '22', rewind: '20岁', gender: '演示', family: '演示', status: '演示',
    }))
    localStorage.removeItem('life-backtest.garden.v2')
  })
  await page.setViewportSize({ width: 1536, height: 864 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/?scene=garden')
  const garden = page.locator('.garden-scene')
  await expect(garden).toBeVisible()
  await expect(garden).toHaveAttribute('data-current-age', '22')
  await expect(garden).toHaveAttribute('data-garden-phase', 'era')
  await expect(page.getByRole('button', { name: '25岁', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '30岁', exact: true })).toHaveCount(0)
  await expect(page.locator('[data-action="chapters"]')).toBeHidden()
  await page.getByRole('button', { name: '20岁', exact: true }).click()
  await expect.poll(async () => page.locator('.garden-choice-flower.is-landed').count(), { timeout: 4000 }).toBeGreaterThanOrEqual(6)
  await page.locator('.garden-choice-flower').first().click()
  await page.locator('.garden-choice-flower').first().click()
  await expect(garden).toHaveAttribute('data-garden-phase', 'npc', { timeout: 18_000 })
  await page.getByRole('button', { name: '进入下一个时间点 →' }).click()
  await expect(garden).toHaveAttribute('data-age', '22')
  await expect(garden).toHaveAttribute('data-garden-phase', 'era')
  await page.getByRole('button', { name: '查看这一年的选择 ↗' }).click()
  await expect(page.locator('.garden-choice-flower.is-landed').first()).toBeVisible({ timeout: 4000 })
  await page.locator('.garden-choice-flower').first().click()
  await page.locator('.garden-choice-flower').first().click()
  await expect(garden).toHaveAttribute('data-garden-phase', 'npc', { timeout: 18_000 })
  await page.getByRole('button', { name: '这一年已是现在 · 前往三岔口 →' }).click()
  await expect(garden).toHaveAttribute('data-garden-phase', 'crossroads', { timeout: 8_000 })
  await expect(page.getByRole('button', { name: '前往分岔口 →' })).toHaveCount(0)
  await expect(page.locator('.garden-copy')).toBeHidden()
  await expect(page.locator('.garden-timeline')).toBeHidden()
  await expect(page.locator('.garden-signals')).toBeHidden()
  await expect(page.locator('.garden-player')).toBeHidden()
  await expect(page.locator('.garden-orbit-ship')).toBeVisible()
  await expect(page.locator('.garden-orbit-sky')).toBeVisible()
  await expect(page.locator('.garden-galaxy')).toBeVisible()
  await expect(page.locator('.garden-orbit-ship')).toHaveCount(1)
  await expect(page.locator('.garden-location span')).toHaveText('月面三岔口')
  await expect(page.locator('.garden-crossroads-note')).toContainText('时间从这里分成三条')
  await expect(page.getByRole('button', { name: '回溯 · 重访改造的那条路' })).toBeVisible()
  await expect(page.getByRole('button', { name: '前瞻 · 看 23–25 岁的可能' })).toBeVisible()
  await expect(page.getByRole('button', { name: '结束 · 把选择停在这一刻' })).toBeVisible()
  await expect(page.getByRole('button', { name: '前进 · 跟随着人生的继续' })).toHaveCount(0)
  await expect(page.locator('.garden-hole-world')).toHaveCount(3)
  await expect(page.locator('.garden-hole-core')).toHaveCount(0)
  await page.screenshot({ path: 'playtest/garden-06-crossroads.png' })
  await page.getByRole('button', { name: '回溯 · 重访改造的那条路' }).click()
  await expect(garden).toHaveAttribute('data-garden-phase', 'rift')
  await expect(garden).toHaveAttribute('data-rift-kind', 'backtrack')
  await expect(page.locator('.garden-rift')).toContainText('有些人生没有消失')
  await expect(page.locator('.garden-agent-star')).toBeVisible()
  await expect(page.locator('.garden-agent-dialog')).toHaveCount(0)
  await expect(page.locator('.garden-agent-canvas')).toBeVisible()
  await page.waitForTimeout(400)
  await page.screenshot({ path: 'playtest/garden-07-another-me-appear.png' })
  await page.getByRole('button', { name: '走近看看' }).click()
  await expect(page.locator('.garden-agent-year')).toContainText('20 岁')
  await expect(page.locator('.garden-agent-era')).toBeVisible()
  await expect(page.locator('.garden-agent-options button')).toHaveCount(4)
  await expect(page.locator('.garden-agent-match')).toHaveCount(0)
  await page.locator('.garden-agent-options button').first().click()
  await expect(page.locator('.garden-agent-cost')).toHaveCount(4)
  await expect(page.locator('.garden-agent-year')).toContainText('好处')
  await expect(page.locator('.garden-agent-year')).toContainText('结果')
  await page.screenshot({ path: 'playtest/garden-07-another-me-talk.png' })
  await page.getByRole('button', { name: /走到 22 岁/ }).click()
  await expect(page.locator('.garden-agent-year')).toContainText('22 岁 · 现年')
  await expect(page.locator('.garden-agent-match')).toHaveCount(0)
  await page.locator('.garden-agent-options button').first().click()
  await page.getByRole('button', { name: '这一路走到了现在' }).click()
  await expect(page.locator('.garden-agent-match')).toHaveCount(4)
  await expect(page.locator('.garden-agent-match.is-A')).toHaveCount(2)
  await expect(page.locator('.garden-agent-match.is-B')).toHaveCount(2)
  await page.getByRole('button', { name: '……' }).click()
  await expect(page.locator('.garden-rift')).toContainText('剩下的路，你来走')
  await page.getByRole('button', { name: '看他离开' }).click()
  await expect(page.locator('.garden-rift')).toContainText('你看见了两种人生')
  await page.screenshot({ path: 'playtest/garden-07-backtrack.png' })
  await page.getByRole('button', { name: '返回三岔口' }).first().click()
  await expect(garden).toHaveAttribute('data-garden-phase', 'crossroads')
  await page.getByRole('button', { name: '前瞻 · 看 23–25 岁的可能' }).click()
  await expect(page.getByRole('heading', { name: '23 → 24 → 25 岁可能的走向' })).toBeVisible({ timeout: 8_000 })
  await expect(page.locator('.garden-rift')).toContainText('第五幕')
  await expect(page.locator('.garden-rift')).toContainText('不是命运定论')
  await expect(page.getByText('概率推演，非命运定论')).toBeVisible()
  await page.locator('.garden-rift-npc').first().click()
  await expect(page.locator('.garden-rift-dossier')).toBeVisible()
  await expect(page.locator('.garden-rift-beat')).toHaveCount(3)
  await expect(page.locator('.garden-rift-options button')).toHaveCount(0)
  await expect(page.locator('.garden-rift-explain')).toBeVisible()
  await expect(page.locator('.garden-rift-dossier')).toContainText('当时')
  await expect(page.locator('.garden-rift-archive-post')).toHaveCount(3)
  await expect(page.locator('.garden-rift-archive')).toContainText('TA 写过的')
  await page.getByRole('button', { name: '返回三岔口' }).first().click()
  await expect(garden).toHaveAttribute('data-garden-phase', 'crossroads')
  await page.getByRole('button', { name: '前瞻 · 看 23–25 岁的可能' }).click()
  await expect(page.getByRole('heading', { name: '23 → 24 → 25 岁可能的走向' })).toBeVisible({ timeout: 8_000 })
  await expect(page.getByRole('button', { name: '个人标签' })).toBeVisible()
  await page.getByRole('button', { name: '写下个人展望' }).click()
  await expect(page.locator('.personal-tag-panel')).toBeVisible()
  await expect(page.locator('.personal-tag-profile')).toContainText('现在的年龄')
  await expect(page.locator('.personal-tag-profile')).toContainText('22')
  await expect(page.locator('.personal-tag-choices')).toContainText('岁')
  await page.locator('.personal-tag-form textarea[name="plans"]').fill('先验证再决定')
  await page.locator('.personal-tag-form button[type="submit"]').click()
  await expect(page.locator('.personal-tag-panel')).toBeHidden()
  await page.getByRole('button', { name: '返回三岔口' }).first().click()
  await page.getByRole('button', { name: '结束 · 把选择停在这一刻' }).click()
  await expect(page.getByRole('heading', { name: /有了不一样的体会/ })).toBeVisible({ timeout: 8_000 })
  await expect(page.getByText('阅读原文（演示）')).toBeVisible()
  await page.getByRole('button', { name: '返回三岔口' }).first().click()
  await expect(garden).toHaveAttribute('data-garden-phase', 'crossroads')
})

test('left dialog plants the same way as orbs, and R unsticks the scene', async ({ page }) => {
  await page.addInitScript(() => localStorage.removeItem('life-backtest.garden.v2'))
  await page.setViewportSize({ width: 1536, height: 864 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/?debug=garden')
  const garden = page.locator('.garden-scene')
  await page.getByRole('button', { name: '0岁', exact: true }).click()
  await expect(page.locator('.garden-choice-flower canvas').first()).toBeVisible({ timeout: 4000 })
  await expect(page.locator('.garden-choice-flower canvas')).toHaveCount(await page.locator('.garden-choice-flower').count())
  await expect(page.locator('.garden-choice-flower small').first()).toContainText('%')
  await page.locator('.garden-choice-stat').first().click()
  await expect(garden).toHaveAttribute('data-garden-phase', 'inspect')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('这条路')
  await page.locator('.garden-choice-stat').first().click()
  await expect(garden).toHaveAttribute('data-actor-phase', 'walking', { timeout: 8000 })
  await page.getByRole('button', { name: /重新进入画面/ }).click()
  await expect(garden).toHaveAttribute('data-actor-phase', 'idle')
  await expect(garden).toHaveAttribute('data-age', '0')
  await expect(page.locator('.garden-ground-flower')).toHaveCount(0)
  await page.getByRole('button', { name: '个人标签' }).click()
  const panel = page.locator('.personal-tag-panel')
  await expect(panel).toBeVisible()
  expect(await panel.evaluate(el => getComputedStyle(el).overflowY)).toBe('auto')
  await panel.evaluate(el => { el.scrollTop = 24 })
  expect(await panel.evaluate(el => el.scrollTop)).toBeGreaterThanOrEqual(0)
})
