import { expect, test } from '@playwright/test'

test('flowers respond on hover, plant once, save notes and extend beyond seventy', async ({ page }) => {
  test.setTimeout(150_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 1536, height: 864 })
  await page.goto('/?scene=garden')
  const garden = page.locator('.garden-scene')
  await expect(garden).toBeVisible()
  await page.getByRole('button', { name: '确认回溯年龄 →' }).click()
  await page.getByRole('textbox', { name: '确认回溯年龄', exact: true }).fill('22')
  await page.getByRole('button', { name: '记录', exact: true }).click()
  const bud = page.getByRole('button', { name: '20—30岁 · 待放', exact: true })
  await bud.hover()
  await expect(bud).toHaveAttribute('data-planted', 'false')
  await page.screenshot({ path: 'playtest/garden-01-hover.png' })
  await bud.click()
  await expect(garden).toHaveAttribute('data-actor-phase', 'walking')
  await page.waitForTimeout(850)
  await page.screenshot({ path: 'playtest/garden-motion-01-walking.png' })
  await expect(garden).toHaveAttribute('data-actor-phase', 'kneeling', { timeout: 8000 })
  await page.waitForTimeout(420)
  await page.screenshot({ path: 'playtest/garden-motion-02-kneeling.png' })
  await expect(bud).toHaveClass(/is-planting/, { timeout: 8000 })
  await page.waitForTimeout(250)
  await page.screenshot({ path: 'playtest/garden-02-growing.png' })
  await expect(bud).toHaveAttribute('data-planted', 'true', { timeout: 10_000 })
  await bud.click()
  await page.getByRole('textbox', { name: '留给这一岁的记录' }).fill('我想回看毕业时的选择')
  await page.getByRole('button', { name: '记录', exact: true }).click()
  await expect(page.locator('.garden-form output')).toContainText('已记录')
  await page.screenshot({ path: 'playtest/garden-03-record.png' })
  await page.getByRole('button', { name: '关闭时间档案' }).click()
  const feetBefore = await garden.getAttribute('data-actor-x')
  await page.keyboard.press('ArrowRight')
  await expect(garden).toHaveAttribute('data-age', '25')
  await page.keyboard.press('ArrowLeft')
  await expect(garden).toHaveAttribute('data-age', '22')
  await expect(garden).toHaveAttribute('data-actor-x', feetBefore!)
  for (const label of ['30—40岁 · 盛放', '40—50岁 · 初落', '50—60岁 · 渐落', '60—70岁 · 结籽', '70岁以后 · 延续']) {
    if (label.startsWith('40')) await page.getByRole('button', { name: '40岁以后的时光 →' }).click()
    await page.getByRole('button', { name: label, exact: true }).click()
    await expect(page.getByRole('button', { name: label, exact: true })).toHaveAttribute('data-planted', 'true', { timeout: 18_000 })
  }
  await page.getByRole('button', { name: '80岁', exact: true }).click()
  await expect(garden).toHaveAttribute('data-age', '80')
  await page.screenshot({ path: 'playtest/garden-04-eighty.png' })
  await page.getByRole('button', { name: '回到回溯起点 ↖' }).click()
  await expect(garden).toHaveAttribute('data-age', '22')
  await page.reload()
  await expect(garden).toHaveAttribute('data-age', '22')
  await page.getByRole('button', { name: '20—30岁 · 待放', exact: true }).click()
  await expect(page.locator('.garden-records')).toContainText('我想回看毕业时的选择', { timeout: 10_000 })
  await page.getByRole('button', { name: '关闭时间档案' }).click()
  await page.getByRole('button', { name: '◇ 同代 · 相近选择', exact: true }).click()
  await expect(page.locator('.garden-panel-copy')).toContainText('目前尚未连接')
  expect(errors).toEqual([])
})

test('the garden stays usable in portrait and with reduced motion', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/?scene=garden')
  await expect(page.locator('.garden-scene')).toBeVisible()
  await page.getByRole('button', { name: '确认回溯年龄 →' }).click()
  await page.getByRole('textbox', { name: '确认回溯年龄', exact: true }).fill('35')
  await page.getByRole('button', { name: '记录', exact: true }).click()
  await page.getByRole('button', { name: '30—40岁 · 盛放', exact: true }).click()
  await expect(page.getByRole('button', { name: '30—40岁 · 盛放', exact: true })).toHaveAttribute('data-planted', 'true', { timeout: 10_000 })
  await page.getByRole('button', { name: '更晚的年龄' }).click()
  await expect(page.locator('.garden-scene')).toHaveAttribute('data-age', '37')
  await page.screenshot({ path: 'playtest/garden-05-portrait.png', fullPage: true })
  expect(await page.locator('.garden-frame').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
})

test('R interrupts travel without teleporting, planting or overwriting the selected age', async ({ page }) => {
  await page.goto('/?scene=garden')
  const garden = page.locator('.garden-scene')
  await page.getByRole('button', { name: '0—10岁 · 种子', exact: true }).click()
  await expect(garden).toHaveAttribute('data-actor-phase', 'walking')
  await page.waitForTimeout(800)
  await page.keyboard.press('r')
  await expect(garden).toHaveAttribute('data-actor-phase', 'idle')
  const feet = await garden.getAttribute('data-actor-x')
  await page.waitForTimeout(1200)
  await expect(garden).toHaveAttribute('data-actor-x', feet!)
  await expect(garden).toHaveAttribute('data-age', '0')
  await expect(page.getByRole('button', { name: '0—10岁 · 种子', exact: true })).toHaveAttribute('data-planted', 'false')
  await page.getByRole('button', { name: '与主角打个招呼' }).click()
  await expect(page.locator('.garden-note')).toContainText('我会陪你走过去')
  await page.screenshot({ path: 'playtest/garden-motion-03-cancel.png' })
})
